databases:
  - name: dialogo_DB
    databaseName: dialogo_db
    user: Dialogo
    region: singapore

services:
  - type: web
    name: Dialogo
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dialogo_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
